# cosmos_client.py
# ===== generated by gpt to test COSMOS_KEY v/s UAMI =====
"""
Cosmos DB access layer.

Authentication is selected using COSMOS_AUTH_MODE:

    key
        COSMOS_ENDPOINT + COSMOS_KEY

    connection_string
        COSMOS_CONNECTION_STRING

    uami
        COSMOS_ENDPOINT + Azure DefaultAzureCredential

For UAMI mode, the application is expected to run under
AKS Workload Identity.
"""

import os

from dotenv import load_dotenv
from azure.identity import DefaultAzureCredential
from azure.cosmos.aio import CosmosClient
from azure.cosmos import exceptions

load_dotenv()

COSMOS_AUTH_MODE = os.getenv("COSMOS_AUTH_MODE", "uami")

COSMOS_DATABASE = os.environ["COSMOS_DATABASE"]
COSMOS_CONTAINER = os.environ["COSMOS_CONTAINER"]

_credential = None


if COSMOS_AUTH_MODE == "key":
    COSMOS_ENDPOINT = os.environ["COSMOS_ENDPOINT"]
    COSMOS_KEY = os.environ["COSMOS_KEY"]
    _client = CosmosClient(
        url=COSMOS_ENDPOINT,
        credential=COSMOS_KEY,
    )


elif COSMOS_AUTH_MODE == "connection_string":
    COSMOS_CONNECTION_STRING = os.environ["COSMOS_CONNECTION_STRING"]
    _client = CosmosClient.from_connection_string(
        COSMOS_CONNECTION_STRING
    )

elif COSMOS_AUTH_MODE == "uami":
    COSMOS_ENDPOINT = os.environ["COSMOS_ENDPOINT"]
    _credential = DefaultAzureCredential()
    _client = CosmosClient(
        url=COSMOS_ENDPOINT,
        credential=_credential,
    )


else:
    raise ValueError(
        f"Unsupported COSMOS_AUTH_MODE: {COSMOS_AUTH_MODE}. "
        "Use: key, connection_string, or uami."
    )


_database = _client.get_database_client(COSMOS_DATABASE)
_container = _database.get_container_client(COSMOS_CONTAINER)


async def create_idea(item: dict) -> dict:
    return await _container.create_item(body=item)


async def list_ideas(limit: int = 50) -> list[dict]:
    query = "SELECT * FROM c ORDER BY c.created_at DESC OFFSET 0 LIMIT @limit"

    results = _container.query_items(
        query=query,
        parameters=[{"name": "@limit", "value": limit}],
    )

    return [item async for item in results]


async def get_idea(idea_id: str) -> dict | None:
    try:
        return await _container.read_item(
            item=idea_id,
            partition_key=idea_id,
        )

    except exceptions.CosmosResourceNotFoundError:
        return None


async def close():
    await _client.close()

    if _credential:
        await _credential.close()



# ===== was initially generated by claude =====
# """
# Cosmos DB access layer.

# Deliberately absent from this file: any key, connection string, or secret.

# DefaultAzureCredential, when running as a pod labeled
# `azure.workload.identity/use: "true"` under a ServiceAccount annotated with
# the UAMI's client ID, transparently:
#   1. Reads the projected OIDC token the azure-wi-webhook mounted into the pod
#      (AZURE_FEDERATED_TOKEN_FILE).
#   2. Exchanges it with Azure AD for a short-lived access token scoped to
#      Cosmos DB, using the federated identity credential trust set up in
#      Terraform (identity.tf).
#   3. Caches and refreshes that token automatically for every SDK call below.

# Locally (outside AKS), the same code falls back to `az login` credentials or
# env-var service principal credentials - same code path, no branching needed
# for "local dev" vs "in-cluster", which is itself a nice side effect of using
# the Azure Identity SDK chain instead of hand-rolled auth.
# """

# import os
# from azure.identity import DefaultAzureCredential
# from azure.cosmos.aio import CosmosClient
# from azure.cosmos import exceptions

# COSMOS_ENDPOINT = os.environ["COSMOS_ENDPOINT"]  # not a secret - just a URL
# COSMOS_DATABASE = os.environ["COSMOS_DATABASE"]
# COSMOS_CONTAINER = os.environ["COSMOS_CONTAINER"]

# _credential = DefaultAzureCredential()
# _client = CosmosClient(url=COSMOS_ENDPOINT, credential=_credential)
# _database = _client.get_database_client(COSMOS_DATABASE)
# _container = _database.get_container_client(COSMOS_CONTAINER)


# async def create_idea(item: dict) -> dict:
#     return await _container.create_item(body=item)


# async def list_ideas(limit: int = 50) -> list[dict]:
#     query = "SELECT * FROM c ORDER BY c.created_at DESC OFFSET 0 LIMIT @limit"
#     results = _container.query_items(
#         query=query,
#         parameters=[{"name": "@limit", "value": limit}],
#     )
#     return [item async for item in results]


# async def get_idea(idea_id: str) -> dict | None:
#     try:
#         return await _container.read_item(item=idea_id, partition_key=idea_id)
#     except exceptions.CosmosResourceNotFoundError:
#         return None


# async def close():
#     await _client.close()
#     await _credential.close()
